### ISSUE TITLE
Changing VerificationCodeInput length

### ISSUE THREAD

**Issue by mopilo** [tinylife-io/flutter_verification_code_input#1]
I changed the length of VerificationCodeInput form 4 to 6 and I'm having errors like this.
RangeError (index): Invalid value: Not in range 0..3, inclusive: 4

**Comment by nploi** [comment]
Hi @mopilo,
If you change the length of VerificationCodeInput, you press "R" to Performing hot restart.

**Comment by mopilo** [comment]
okay thanks.

**Comment by TheJltres** [comment]
That's not all, List FocusNode in initState, doesn't complete, you do widget.lenght, but sometimes if lengh is changed, so you have to put the lenght of user input parameter

Fails for me
```  @override
  void initState() {
    if (_listFocusNode.isEmpty) {
      for (var i = 0; i < widget.length; i++) {
        _listFocusNode.add(new FocusNode());
        _listControllerText.add(new TextEditingController());
        _code[i] = " ";
      }
    }
    super.initState();
  }
```
Works changing lenght of class like u said before
```  @override
  void initState() {
    if (_listFocusNode.isEmpty) {
      for (var i = 0; i < VerificationCodeInput().length; i++) {
        _listFocusNode.add(new FocusNode());
        _listControllerText.add(new TextEditingController());
        _code[i] = " ";
      }
    }
    super.initState();
  }
```
