### ISSUE TITLE
How to disable autofocus?

### ISSUE THREAD

**Issue by lucasbar1981** [tinylife-io/flutter_verification_code_input#3]
Hi there, 

How can I avoid the autofocus when loading a screen that contains this resource? 

Thank you.

**Comment by shubhamnatani** [comment]
in the last text field the inputfield acccept only one value but it accept more two.!
So how i can stop taking extra value.

**Comment by nploi** [comment]
Hi @lucasbar1981,
I fixed,
Thank you !!
