### ISSUE TITLE
The Screen will crash after navigate back then return to it again

### ISSUE THREAD

**Issue by ahmedmehanna** [tinylife-io/flutter_verification_code_input#8]
### The Problem
the screen who has the verify widget is crashing.

### The Scenario
I created a sample flutter app has two screens

- Home screen
- Verify screen

Navigate from Home screen to Verify screen, go back to Home screen then navigate again to Verify screen.
The Verify screen will crash.

### Screenshot

![image](https://user-images.githubusercontent.com/966313/74477442-3b50ac80-4ea3-11ea-8706-87eac3353b02.png)

### The Flutter App (Source Code)

[test_verification_code.zip](https://github.com/tiny-express/flutter_verification_code_input/files/4201020/test_verification_code.zip)

**Comment by nploi** [comment]
I will check for errors, thank you.

**Comment by nploi** [comment]
Hi @ahmedmehanna.
The package you are using is not this package.
